apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-server-secrets-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: identity-server-secrets
    template:
      metadata:
        labels:
        {{- include "common-config.labels" . | nindent 10 }}
      type: kubernetes.io/secret
      engineVersion: v2
      data:
        ConnectionStrings__IdentityConnection: {{`"{{ .connectionstring }}"`}}
        ConnectionStrings__RedisCache: {{`"{{ .redis_host }}:6379,password={{ .redis_password }}"`}}
        ProviderSettings__GoogleClientId: {{ `"{{ .google_clientid }}"` }}
        ProviderSettings__GoogleClientSecret: {{ `"{{ .google_secret }}"` }}
        
  data:
  - secretKey: connectionstring
    remoteRef:
      key: secrets-k8/identity/{{ .Values.vault.environment }}/connections
      property: connectionstring
  - secretKey: google_clientid
    remoteRef:
      key: secrets-k8/identity/{{ .Values.vault.environment }}/providers/google
      property: clientid
  - secretKey: google_secret
    remoteRef:
      key: secrets-k8/identity/{{ .Values.vault.environment }}/providers/google
      property: clientsecret
  - secretKey: redis_password
    remoteRef:
      key: secrets-k8/redis/{{ .Values.redis.environment }}
      property: password
  - secretKey: redis_host
    remoteRef:
      key: secrets-k8/redis/{{ .Values.redis.environment }}
      property: host
